Apollo
quantifiedstudent/web-api pull request #2
Opened 2022-06-03 10:18 UTC by kanersps

ADD REAL DESCRIPTION HERE

This was created to leave comments for code

2022-06-03 10:21 UTC, kanersps commented
@waltersajtos please remove the .idea directory and add it to gitignore

2022-06-23 15:59 UTC, Typiqally requested changes
Very good work so far! I'm not sure whether it is possible with the time remaining, but I would like to see the code base migrated to TypeScript instead of JavaScript to ensure that the project stays modern.

2022-06-23 15:59 UTC, Typiqally commented on src/apollo-server.js
> +];
Please move this and following to a separate file to create more overview.

```ts
const CanvasData = require("./dataSources/canvas");
const WatchData = require("./dataSources/smartWatch");
const LoggingPlugin = require("./plugins/logging");
```

2022-06-23 15:59 UTC, Typiqally commented on src/dataSources/canvas/canvas-api.js
> +        console.log(this.context.Authorization)
This log is probably here for debugging purposes, but please remove before merging

2022-06-23 15:59 UTC, Typiqally commented on src/plugins/logging.js
> +const loggingPlugin = {
Is this still used?

2022-06-23 15:59 UTC, Typiqally commented on src/dataSources/smartWatch/watch-api.js
> +const StressData = require('./stress-data');
Maybe move this to a mock directory to make it clearer that it is mock data

2022-10-04 12:19 UTC, closed without merging